config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  resources 'events'
  resources 'grades'
  resources 'time_tables'
  resource 'locales'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users, join_table: 'events_users'

  validates :place, presence: true
  validates :title, presence: true
  validates :date_from, presence: true
  validates :date_to, presence: true
  validates_datetime :date_from, :after => lambda { DateTime.current }
  validates_datetime :date_to, :after => lambda { DateTime.current }
  validates_datetime :date_to, :after => :date_from
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :user
  validates :grade_value, :lecture, presence: { message: "must be present"}

  validates :grade_value, numericality: { message: "Must be a number" }
  validates :grade_value, numericality: {:greater_than_or_equal_to => 1.0, message: I18n.t('grades.grade_greater_1')}
  validates :grade_value, numericality: {:less_than_or_equal_to => 4.0, message: I18n.t('grades.grade_less_4')}
end

app/models/table_row.rb
class TableRow < ApplicationRecord
  belongs_to :time_table

  validates :period, presence: true
end

app/models/time_table.rb
class TimeTable < ApplicationRecord
  belongs_to :user

  has_many :table_rows
  accepts_nested_attributes_for :table_rows

  validates :caption, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:github]

  has_and_belongs_to_many :events, join_table: 'events_users'
  has_many :grades
  has_one :time_table

  has_attached_file :image, default_url: ActionController::Base.helpers.asset_path("default-avatar.png")
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :image])
  end

  def set_locale
    cookies[:locale] = params.permit(:locale)[:locale] if params.permit(:locale)[:locale].present?
    I18n.locale = cookies[:locale]
  end # #set_locale


end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action

  def index
    @events = Event.where('date_to > ?', DateTime.current)
                  .joins(:users)
                  .merge(User.where("user_id = ?", current_user.id))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = t('events.event_saved')
    else
      flash[:alert] = @event.errors.full_messages.map(&:inspect).join(', ')
    end

    @event.users.each do |participant|
      EventMailer.notify_event_participants(@event, current_user, participant).deliver
    end

    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:date_from, :date_to, :place, :title, user_ids: [])
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:destroy]

  def index
    @grade = Grade.new
    @grades = Grade.where('user_id = ?', current_user.id)
  end

  def create
    @grade = Grade.new(grade_params)
    @grade.user = current_user

    @grade.grade_value = @grade.grade_value.round(2)

    if @grade.save
      flash[:notice] = t('controllers.grades_controller.grade_saved')
    else
      flash[:alert] = @grade.errors.full_messages.map(&:inspect).join(',')
    end

    redirect_to grades_path
  end

  def destroy
    @grade.destroy

    redirect_to grades_path
  end

  private

  def grade_params
    params.require(:grade).permit(:grade_value, :lecture, :id)
  end

  def set_grade
    @grade = Grade.find(params[:id])
  end

  def round_to
    float fl = (10 ** 2).to_f
    nr = self * f
    nr.round / f
  end

  def get_average_grade_point
    if current_user.grades.pluck("avg(grade_value)").join(',') != ""
      "%0.2f" % [current_user.grades.pluck("avg(grade_value)").join(',')]
    else
      t('controllers.grades_controller.grade_not_found')
    end
  end

  helper_method :get_average_grade_point
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  def update
    I18n.locale = params.permit(:locale)[:locale]
    redirect_back(fallback_location: root_path)
  end # #update
end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @time_table = TimeTable.find_by('user_id = ?', current_user.id)
  end

  def edit
  end

  def update
    @time_table.update_attributes(time_table_params)
    redirect_to time_tables_path
  end

  def create
    @time_table = TimeTable.new(time_table_params)
    @time_table.user = current_user

    if @time_table.save
      flash[:notice] = t('timetable.timetable_saved')
    else
      flash[:alert] = @time_table.errors.full_messages.map(&:inspect).join(', ')
    end

    redirect_to time_tables_path
  end

  def new
    @time_table = TimeTable.new
    1.times {@time_table.table_rows.build}
  end

  def destroy
     if @time_table.destroy
       flash[:notice] = t('timetable.timetable_deleted')
     else
       flash[:alert] = t('timetable.timetable_not_deleted')
     end

    redirect_to time_tables_path
  end

  private

  def set_post
    @time_table = TimeTable.find(params[:id])
  end

  def time_table_params
    params.require(:time_table).permit(:caption, table_rows_attributes:
        [:id, :order, :period, :monday_field, :tuesday_field,
         :wednesday_field, :thursday_field, :friday_field, :saturday_field])
  end

  def return_to_break(string)
    string.gsub(/\n/, '<br>').html_safe
  end

  helper_method :return_to_break
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/table_rows_helper.rb
module TableRowsHelper
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<%= button_to t('events.new_event'), new_event_path, method: :get, :class => 'btn btn-success btn-new-event' %>

<div class="container">
  <table class="table table-hover">
    <thead>
    <tr>
      <th> <%= t('events.date_from') %> </th>
      <th> <%= t('events.date_to') %> </th>
      <th> <%= t('events.title') %> </th>
      <th> <%= t('events.place') %> </th>
      <th> <%= t('events.participants') %> </th>
    </tr>
    </thead>

    <tbody>
    <% if !@events.blank? %>
      <% for item in @events %>
        <tr>
          <td> <%= item.date_from.strftime("%F  %T") %> </td>
          <td> <%= item.date_to.strftime("%F  %T") %> </td>
          <td> <%= item.title %> </td>
          <td> <%= item.place %> </td>
          <td>
            <% item.users.each do |user| %>
             <%= user.email %>
             <br/>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="col-sm-5">
    <%= simple_form_for @event do |f| %>
      <%= f.label t('events.date_from')%><br/>
      <%= f.datetime_select :date_from %><br/><br/>
      <%= f.label t('events.date_to') %><br/>
      <%= f.datetime_select :date_to, label: t('events.date_to') %>
      <br/>
      <br/>
      <%= f.input :place, as: :string, label: false, input_html: {autocomplete: 'off'},
              placeholder: t('events.place') %>
      <%= f.input :title, label: false, input_html: {autocomplete: 'off'},
              placeholder: t('events.title') %>
      <%= f.association :users, label_method: :email %>
      <%= f.submit t('button_lables.save'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= button_to t('events.new_event'), new_events_path, method: :get, :class => 'btn btn-success btn-new-event' %>

<div class="container">
  <table class="table table-hover">
    <thead>
    <tr>
      <th> <%= t('events.date_from') %> </th>
      <th> <%= t('events.date_to') %> </th>
      <th> <%= t('events.title') %> </th>
      <th> <%= t('events.place') %> </th>
      <th> <%= t('events.participants') %> </th>
    </tr>
    </thead>

    <tbody>
    <% if !@events.blank? %>
      <% for item in @events %>
        <tr>
          <td> <%= item.date_from.strftime("%F  %T") %> </td>
          <td> <%= item.date_to.strftime("%F  %T") %> </td>
          <td> <%= item.title %> </td>
          <td> <%= item.place %> </td>
          <td>
            <% item.users.each do |user| %>
             <%= user.email %>
             <br/>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/grades/_add_new_grade.html.erb
<div class="new-grade">
  <h3>
    <%= t('.my_grades') %>
  </h3>

  <div class="container">
    <div class="col-sm-5">
      <h3>
        <%= t('.add_new_grade') %>
      </h3>
      <%= simple_form_for @grade do |f| %>
        <%= f.input :grade_value, as: :string, label: false, input_html: {autocomplete: 'off'},
                    placeholder: t('.grade_text_field') %>
        <%= f.input :lecture, label: false, input_html: {autocomplete: 'off'},
                    placeholder: t('.lecture_text_field') %>
        <%= f.error :grade_value %>
        <%= f.error :lecture %>
        <%= f.submit t('.save_grade_button'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/grades/_all_grades.html.erb
<div class="all-grades">
  <h3>
    <%= t('.grades') %>
  </h3>

  <div class="container">
    <table class="table table-hover gradeTable">
      <thead>
      <tr>
        <th> <%= t('.thead_grade') %> </th>
        <th> <%= t('.thead_lecture') %> </th>
      </tr>
      </thead>

      <tbody>
      <% if !@grades.blank? %>
        <% for item in @grades %>
          <tr>
            <td> <%= item.grade_value %> </td>
            <td> <%= item.lecture %> </td>
            <td> <%= link_to t('.remove_grade'), grade_path(item), method: :delete,
                             data: {confirm: t('.remove_grade_confirmation')} %> </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/grades/_average_gradepoint.html.erb
<div class="average-grade">
  <h3>
    <%= t('.grade_point_average') %>
    <%= get_average_grade_point %>
  </h3>
</div>

app/views/grades/_show_grades.html.erb
<div class="all-grades">
  <h1>
    <%= t('.grades') %>
  </h1>

  <div class="container">
    <table class="table table-hover gradeTable">
      <thead>
      <tr>
        <th> <%= t('.thead_grade') %> </th>
        <th> <%= t('.thead_lecture') %> </th>
      </tr>
      </thead>

      <tbody>
      <% if !@grades.blank? %>
        <% @grades.each do |book| %>
          <tr>
            <td> <%= book.grade_value %> </td>
            <td> <%= book.lecture %> </td>
            <td> <%= link_to t('.remove_grade'), book, method: :delete,
                             data: {confirm: t('.remove_grade_confirmation')} %> </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/grades/index.html.erb
<div class="container-fluid">

  <%= render 'add_new_grade' %>

  <%= render 'average_gradepoint' %>

  <%= render 'all_grades' %>

</div>

app/views/grades/show.html.erb
<div class="container-fluid">

  <%= render 'add_new_grade' %>

  <%= render 'average_gradepoint' %>

  <%= render 'show_all_grades' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('application_name') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-light bg-light navbar-inverse">
  <a class="navbar-brand link-item" href="/">
    Home
  </a>

  <%= link_to (t '.time_table'), time_tables_path, method: :get, :class => "navbar-brand link-item" %>

  <%= link_to (t '.grades'), grades_path, method: :get, :class => "navbar-brand link-item" %>

  <%= link_to (t '.events'), events_path, method: :get, :class => "navbar-brand link-item" %>

  <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => "navbar-brand pull-right link-item" %>
    <a class="navbar-brand pull-right" href=<%= edit_user_registration_path %>>
      <% if current_user.image_file_name? %>
        <%= image_tag current_user.image.url %>
      <% else %>
        <%= image_tag(asset_path('default-avatar.png')) %>
      <% end %>
    </a>
  <% end %>

  <% if user_signed_in? == false %>
    <%= link_to 'Login', new_user_session_path, method: :get, :class => "navbar-brand pull-right link-item" %>
  <% end %>
</nav>


<div class="container-fluid">
  <div class="row">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
  </div>
</div>
<%= yield %>


<footer class="footer">
  <div class="container footer-container">
    <span class="text-muted">
      @<%= t('application_name') %>
    </span>
    <div class="footer-text-rigth">
      <%= link_to t('.english'), locales_path(locale: :en), method: :patch %>
      /
      <%= link_to t('.german'), locales_path(locale: :de), method: :patch %>
    </div>
  </div>
</footer>


</body>
</html>

app/views/time_tables/_time_table_form.html.erb
<%= simple_form_for @time_table do |f| %>
  <div class="container-fluid">
    <div class="col-sm-2">
      <%= f.input :caption, as: :string, label: "Name", input_html: {autocomplete: 'off'} %>
    </div>


    <table class="table" id="time-table-table">
      <thead>
      <tr>
        <th><%= t('timetable.period') %></th>
        <th><%= t('weekday.monday') %></th>
        <th><%= t('weekday.tuesday') %></th>
        <th><%= t('weekday.wednesday') %></th>
        <th><%= t('weekday.thursday') %></th>
        <th><%= t('weekday.friday') %></th>
        <th><%= t('weekday.saturday') %></th>
      </tr>
      </thead>

      <tbody>
      <%= f.nested_fields_for :table_rows, wrapper_tag: :tr do |table_row|%>
        <%= table_row.hidden_field :id %>
        <td><%= table_row.text_area(:period, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:monday_field, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:tuesday_field, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:wednesday_field, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:thursday_field, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:friday_field, cols: "20", rows: "4") %></td>
        <td><%= table_row.text_area(:saturday_field, cols: "20", rows: "4") %></td>
      <% end %>
      </tbody>
    </table>

    <div class="col-sm-2">
      <%= f.add_nested_fields_link :table_rows, t('timetable.add_new_row'), class: 'btn btn-success', role: 'button'  %>
      <%= f.submit t('button_lables.save'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/time_tables/create.html.erb
<h1>Create</h1>

<table>
  <tr>
    <th>von - bis</th>
    <th><%= t('weekday.monday') %></th>
    <th><%= t('weekday.tuesday') %></th>
    <th><%= t('weekday.wednesday') %></th>
    <th><%= t('weekday.thursday') %></th>
    <th><%= t('weekday.friday') %></th>
    <th><%= t('weekday.saturday') %></th>
  </tr>
  <tr>
    <td><textarea>1. Stunde</textarea></td>
    <td><textarea></textarea></td>
    <td><textarea></textarea></td>
    <td><textarea></textarea></td>
    <td><textarea></textarea></td>
    <td><textarea></textarea></td>
    <td><textarea></textarea></td>
  </tr>
</table>

app/views/time_tables/edit.html.erb
<%= render 'time_table_form' %>

app/views/time_tables/index.html.erb
<% if @time_table.present? %>
  <div class="container-fluid">
    <h2 class="time-table-heading">
      <%= @time_table.caption %>
    </h2>

    <br/>
    <br/>

    <table class="time-table table">
      <tr>
        <th class="time-table-row">
          <%= t('timetable.period') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.monday') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.tuesday') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.wednesday') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.thursday') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.friday') %>
        </th>
        <th class="time-table-row">
          <%= t('weekday.saturday') %>
        </th>
      </tr>

    <% @time_table.table_rows.each do |table_row| %>
      <tr>
        <td class="time-table-row">
          <%= return_to_break(table_row.period) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.monday_field) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.tuesday_field) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.wednesday_field) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.thursday_field) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.friday_field) %>
        </td>
        <td class="time-table-row">
          <%= return_to_break(table_row.saturday_field) %>
        </td>
      </tr>
    <% end %>

    </table>
      <div class="time-table-buttons">
        <%= button_to t('button_lables.delete'), time_table_path(@time_table.id),
                      method: :delete, data: {confirm: t('timetable.remove_time_table_confirmation')}, :class => "btn btn-danger" %>
      </div>

      <div class="time-table-buttons">
        <%= button_to t('button_lables.update'), edit_time_table_path(@time_table.id),
                      method: :get, :class => "btn btn-primary" %>
      </div>
  </div>

<% else %>
  <div class="no-timetable">
    <h2><%= t('timetable.no_timetable') %></h2>
    <%= button_to t('timetable.new_timetable'), new_time_table_path, method: :get, :class => "btn btn-success" %>
  </div>
<% end %>

app/views/time_tables/new.html.erb
<%= render 'time_table_form' %>

app/views/welcome/index.html.erb
<h1 class="front-heading"><%= t('application_name') %></h1>

<div class="front-img-div">
  <img class="front-img" src="<%= asset_path('front-img.jpg') %>"/>
</div>

<ul class="feature-list">
  <li><h2><%= t('features.timetable') %></h2></li>
  <li><h2><%= t('features.grade') %></h2></li>
  <li><h2><%= t('features.event') %></h2></li>
</ul>